version: '3.8'

services:
  backend:
    build: ./back-end
    ports:
      - "5252"

  frontend:
    build: ./front-end
    ports:
      - "9000"
    depends_on:
      - backend

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
